[versions]
kotlin = "2.2.0"
chasm = "0.9.66"
kotlinx-coroutines = "1.10.2"
kotlinx-io = "0.7.0"
wasi-emscripten-host = "0.5"

[libraries]
chasm = { group = "io.github.charlietap.chasm", name = "chasm", version.ref = "chasm" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
weh-chasm-wasip1 = { group = "at.released.weh", name = "bindings-chasm-wasip1", version.ref = "wasi-emscripten-host" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
